### ISSUE TITLE
Game crashes when I try to make food production

### ISSUE THREAD

**Issue by Gageowe** [8BitToaster/Grand-Expansion#1]
Whenever I try to build a farm the game crashes

**Comment by THB0705** [comment]
Yep, just clicking on it closes the game immediately :( , I had so much progres...

```
Traceback (most recent call last):
  File "game.py", line 1235, in <module>
    MainMenu(0)
  File "game.py", line 635, in MainMenu
    game_loop()
  File "game.py", line 1153, in game_loop
    draw(i * (640/width),j * (640/height) + 160,"Tile",board[j][i],height,width)
  File "game.py", line 536, in draw
    gameDisplay.blit(Images["City"],(x,y))
KeyError: 'City'
```

**Comment by 8BitToaster** [comment]
Sorry, I'm replying late to this as I didn't see it earlier, but I will look into it. This error is happening because somehow the picture for the city wasn't in the images folder. I'm not sure if it was a mistake on my part or some weird bug, but sorry it happened to you. I haven't encountered the error with the farm, but I have that on my todo list to fix. I'm going to make a little To do list in the project tab of this directory that you guys can check on and maybe suggest things to add.

- 8BitToaster

**Comment by THB0705** [comment]
This issue has been fixed and can be closed.
